{
    "name": "Hospital Management",
    "description": """A Hospital Management app from Heliconia Solutions""",
    "summary": "A simple Hospital Management app",
    "version": "0.0.0",
    "category": "Health and Fitness",
    "sequence": 0,
    "website": "https://www.heliconia.io",
    "author": "Neel Patel (Heliconia Solutions Pvt. Ltd.), ",
    "depends": ["base", "account", "stock", "sale_management"],
    "data": [
        "security/ir.model.access.csv",
        "data/sequence_data.xml",
        "data/hospital_patient_data.xml",
        "data/appoint_email.xml",
        # "views/account_move_view.xml",
        "wizard/hospital_appointment_wizard_view.xml",
        "wizard/patient_mass_edit.xml",
        "reports/hospital_report_templates.xml",
        "reports/hospital_report_actions.xml",
        "reports/report_patient_appointments.xml",
        "views/patient_data.xml",
        "views/doctor_data.xml",
        "views/appointments_data.xml",
        "views/conference_data.xml",
        "views/beds_data.xml",
        "views/res_config_settings_view.xml",
        "views/medicine_view.xml",
        "views/sale_view.xml",
        "views/test_view.xml",
        "views/menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "static/src/icon.png",
        ],
    },
    "installable": True,
    "application": True,
    "license": "LGPL-3",
    "images": ["static/description/icon.png"],
}
