from . import patients
from . import doctors
from . import appointments
from . import conference
from . import beds
from . import res_config_settings
from . import prescription
from . import medicine
from . import sale
