from . import appointment_slots
from . import appointments
from . import beds
from . import conference
from . import doctors
from . import medicine
from . import patients
from . import prescription
from . import res_config_settings
from . import sale
from . import test_file
from . import my_report_layouts
from . import hospital_dashboard
from . import hospital_dashboard_compute
